# Elementary Number Theory

## The natural numbers

Intuitively, the natural numbers consist of $1, 1 + 1, 1+ 1 + 1, \ldots$

How do you know you have captured all natural numbers? How do you know they are all distinct?

We shall assume:

::: {.definition name="Peano Axioms"}

The natural numbers, $\mathbb{N}$, is a set containing a special element '$1$' with an operation '$+1$' satisfying

i. $\forall \; n \in \mathbb{N},\ n + 1 \neq 1$;
ii. $\forall \; m, n \in \mathbb{N},\ \text{ if } m \neq n,\ \text{ then } m + 1 \neq n + 1$
iii. for any property $P(n)$, if $P(1)$ is true and $\forall \; n \in \mathbb{N}, P(n) \implies P(n + 1),$ then $P(n)$ is true for all natural numbers
:::

iii is called the induction axiom.

i and ii capture the idea that any two natural numbers are distinct; iii captures our intuitive notion that the list^[$1, 1 + 1, 1+ 1 + 1, \ldots$] is complete (i.e. encompasses all natural numbers).^[to see this rigorously, take $P(n)$ = "$n$ is on this list]

Now we can write 2 for $1 + 1$, 3 for $1 + 1 + 1$, etc, and we can define an operation '$+k$' for any natural number $k$:
    
$\hspace{1cm}$ for every natural number $n$, we know$n + (k + 1) = (n + k) + 1$;

$\hspace{1cm}$ and so by induction, taking $P(k)$ = "'$+k$' is defined", proved.

Similarly, we can define multiplication, powers, etc. You may check that the "normal" rules of arithmetic apply:

<!--
1. $\forall \; a, b, \in \mathbb{N} \hspace{1cm} a + b = b + a$ [($+$ is commutative);]{style="float:right"}
2. $\forall \; a, b, \in \mathbb{N} \hspace{1.2cm} a b = b a$ ($\times$ is commutative);
3. $\forall \; a, b, c \in \mathbb{N} \hspace{1cm} a + (b + c) = (a + b) + c$ ($+$ is associative);
4. $\forall \; a, b, c \in \mathbb{N} \hspace{1cm} a (b c) = (a b) c$ ($\times$ is associative);
4. $\forall \; a, b, c \in \mathbb{N} \hspace{1cm} a (b + c) = ab + ac$ ($\times$ is distributive over $+$); -->

\begin{align}
    &1.\ \forall \; a, b, \in \mathbb{N}  & &a + b = b + a & &(+ \text{ is commutative}); \\
    &2.\ \forall \; a, b, \in \mathbb{N}  & &ab = ba & &(\times \text{ is commutative}); \\
    &3.\ \forall \; a, b, c \in \mathbb{N} & &a + (b + c) = (a + b) + c & &(+ \text{ is associative}); \\
    &4.\ \forall \; a, b, c \in \mathbb{N} & &a (b c) = (a b) c & &(\times \text{ is associative}); \\
    &5.\ \forall \; a, b, c \in \mathbb{N} & &a (b + c) = ab + ac & &(\times \text{ is distributive over }+);
\end{align} 

**Lecture 3**

We can define $a < b$ if $a + c = b$ for some $c \in \mathbb{N}$. You may want to check

\begin{align}
    &6.\ \forall \; a, b, c & a < b &\implies a + c < b + c \\
    &7.\ \forall \; a, b, c & a < b &\implies a c < b c \\
    &8.\ \forall \; a, b, c & a < b \text{ and } b < c &\implies a < c \\
    &9.\ \forall \; a & &\lnot (a < a).
\end{align} 

Recall the induction axiom: if $P(1)$ holds and $\forall \; n \in \mathbb{N}, P(n) \implies P(n+1)$, then $P(n)$ holds $\forall \; n \in \mathbb{N}$.
This is also known as the *(weak) principle of induction (WPI)*. A more useful form is the *Strong Principle of Induction (SPI)*: if

1. $P(1)$ holds and
2. $\forall \; n \in \mathbb{N}$, we have $P(m) \;\forall \; m \leq n \implies P(n + 1)$, then $P(n)$ holds $\forall \; n \in \mathbb{N}$.

In fact, WPI and SPI are equivalent. SPI $\implies$ WPI should be fairly clear. To see WPI $\implies$ SPI, apply the former to $Q(n) = `P(m) \; \forall \; m \leq n'$

*Well-ordering Principle (WOP)*: If $P(n)$ holds for some $n \in \mathbb{N}$, then there is a least $n \in \mathbb{N}$ s.t. $P(n)$ holds.
An alternative phrasing is "every non-empty subset of $\mathbb{N}$ has a minimal element".

::: {.theorem}
SPI is equivalent to the WOP.
:::

::: {.proof}
To show that WOP implies SPI, we assume 1 and 2 from SPI, and show that $P(n)$ holds $\forall \; n \in \mathbb{N}$ using WOP.

Suppose, on the contrary, that $P(n)$ is not true $\forall \; n \in \mathbb{N}$.
Then $C = {n \in \mathbb{N}: P(n) \text{ is false}} \neq \emptyset$.
By WOP, $C$ has a minimal element, $m$.
Now $\forall \; k < m$, $k \notin C$ (by minimality of $m$), so $P(k)$ holds $\forall \; k < m$.
But by 2 of SPI, $P(m)$ holds, so contradicting $m \in C$. Hence SPI holds.

To show that SPI implies WOP, suppose there is no least $n \in \mathbb{N}$ s.t. $P(n)$ holds.
We want to show that $P(n)$ does not hold for any $n \in \mathbb{N}$, using SPI.

Consider $Q(n) = `\lnot P(n)'$. 
Certainly $P(1)$ is false (else $1$ would be the minimal element), so $Q(1)$ holds.

Given $n \in \mathbb{N}$, suppose that $Q(k)$ is true $\forall \; k < n$.
Then $P(k)$ is false $\forall \; k < n$.
So $P(n)$ is false as otherwise $n$ would be the minimal element for which $P$ holds.
Hence $Q(n)$ is true, and 2 of SPI holds, so $Q(n)$ is true $\forall \; n \in \mathbb{N}$. 
Thus $P(n)$ is false $\forall \; n \in \mathbb{N}$.
:::

WOP enables us to prove $P(n)$ is true $\forall \; n \in \mathbb{N}$ as follows: If not, then there is a minimal counterexample, and we try and derive a contradiction.

## The integers

The integers, written $\mathbb{Z}$, consist of all symbols $n, -n$, where $n \in \mathbb{N}$, and $0$.

We can define $+$ and $\times$ etc on $\mathbb{Z}$ using $\mathbb{N}$, and check that the usual rules of arithmetic hold.
We also have
\begin{align*}
    &10.\ \forall \; a \in \mathbb{Z} & a + 0 &= a & &(\text{identity for } +) \\
    &11.\ \forall \; a \in \mathbb{Z}, & \exists \; b \in \mathbb{Z} \text{ s.t. } a + b &= 0 & &(\text{inverses for } + ) \\
\end{align*} 

Define '$a < b$' if $a + c = b$ for some $c \in \mathbb{N}$. Rules 6, 8, 9 continue to hold, but 7 must be modified

7'. $\forall \; a, b, c \in \mathbb{Z}, a < b \text{ and } c > 0 \implies ac < bc.$

## The rationals
The rationals, written $\mathbb{Q}$, consist of all expressions $\frac{a}{b}$ (note this is not division as we have not defined division, it just looks the same), where $a, b \in \mathbb{Z}$, $b \neq 0$, and $\frac{a}{b}$ and $\frac{c}{d}$ are regarded as the same if $ad = bc$.

Define $\frac{a}{b} + \frac{c}{d} = \frac{ad + bc}{bd}$, and check it does not matter how we wrote $\frac{a}{b}$ or $\frac{c}{d}$.

We similarly define multiplication, and '$\frac{a}{b} < \frac{c}{d}$' where $b, d > 0$ if $ad < bc$. 
You can check all preceding rules apply.

In addition
\begin{align*}
    &12.\ \forall \; a \in \mathbb{Q},\ a \neq 0,\ \exists \; b \text{ s.t. } ab &= 1 & &(\text{inverses for } \times)
\end{align*} 

*Note*. $\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q}$.

## Primes
Given $a, b \in \mathbb{Z}$ we say "$a$ divides $b$" if $\exists \; c \in \mathbb{Z}$ s.t. $b = ac$. We might also say "$a$ is a divisor/ factor of $b$" or "$b$ is a multiple of $a$". We write $a | b$ for $a$ divides $b$.

For any $b \in \mathbb{Z}$, $\pm 1$ and $\pm b$ are always factors; all others are called *proper*.

A natural number $n \geq 2$ is *prime* if its only factors are $\pm 1$ and $\pm n$.^[We don't allow $1$ to be a prime as we want to have unique prime factorisations and it would require every statement to say let $n$ be a prime not equal to $1$.]
If $n \geq 2$ is not prime, then it is *composite*.

::: {.proposition #two}
Every natural number $n \geq 2$ can be written as a product of primes.
:::

**Lecture 4**

::: {.proof}
By induction on $n$. True for $n = 2$.
Let $n > 2$ and suppose that the claim holds up to and including $n - 1$ (SPI). If $n$ is a prime, we are done. If $n$ is composite, then $n = a b$ for some $1 < a, b < n$.
By the induction hypothesis, have $a = p_1 \ldots p_k$, $b = q_1 \ldots q_l$ for some primes $p_1 \ldots p_k, q_1 \ldots q_l$.
Hence $n = ab = p_1 \ldots p_k q_1 \ldots q_l$ is a product of primes.
:::

::: {.theorem}
There are infinitely many primes.
:::

::: {.proof name="Euclid 300 BC"}
Suppose there are finitely many primes, say $p_1, \ldots, p_k$. Let $N = p_1 \ldots p_k + 1$.
Then $p_1 \nmid N$, else $p_1 \mid (N - p_1 \ldots p_k) = 1$. 
Clearly $p_1 \mid 1$ is false.
Likewise, none of $p_2, p_3 \ldots, p_k$ divide $N$, contradicting the fact that $N$ can be written as a product of primes.
:::

Can a number have more than one factorisation in its primes? Our proof of \@ref(prp:2) does not give uniqueness.

Clearly, $21 = 3 \cdot 7$ is unique.
Why is $9049 \cdot 40099 \neq 6701 \cdot 54151$?

We shall need:

::: {.proposition}
If $p$ is a prime and $p \mid ab$ then $p \mid a$ or $p \mid b$.
:::

## Highest Common Factors
Given $a, b \in \mathbb{N}$, a natural number $c$ is the *highest common factor (hcf)*, or *greatest common divisor (gcd)* of $a$ and $b$ if 

i. $c \mid a$ and $c \mid b$ "c is a common divisor of $a$ and $b$"
ii. $d \mid a$ and $d \mid b \implies d \mid c$ "every common factor of $a$ and $b$ divides $c$"

We write $c = \operatorname{hcf}(a, b)$ or $c = \operatorname{g\cdot}(a, b)$, or simply $c = (a, b)$
\begin{align*}
    \text{E.g. the factors of } &12 \text{ are } & &1, 2, 3, 4, 6, 12
    &18 & &1, 2, 3, 6, 9, 18
\end{align*} 
So the common factors are $1, 2, 3, 6$, hence $\operatorname{hcf}(12, 18) = 6$. 
But if $a$ and $b$ had common factors $1, 2, 3, 4, 6$ then $a$ and $b$ would have no $\operatorname{hcf}$ (according to ii).
Therefore, we will need to show that $\operatorname{hcf}(a, b)$ always exists.

::: {.proposition name="Division Algorithm"}
Let $n, k \in \mathbb{N}$. Then we can write $n = qk + r$, where $q$ and $r$ are integers with $0 \leq r \leq k - 1$.
:::

::: {.proof}
By induction on $n$. True for $n = 1$.

Suppose $n - 1 = q k + r$ for some $q, r \in \mathbb{Z}$, $0 \leq r \leq k - 1$.

If $r < k - 1$ then $n = (n - 1) + 1 = qk + (r + 1)$.

If $r = k - 1$ then $n = (n - 1) + 1 = qk + (k - 1) + 1 = (q + 1)k$.
:::

## Euclid's Algorithm

\begin{array}{c|cc|c}
    \text{INPUT} & a & b & a = 372,\ b = 162 \\
    \hline
    \text{STEP } 1& a = q_1 b + r_1 & q_1, r_1 \in \mathbb{Z} & 372 = 2 \cdot 162 + 48 \\
    & & 0 \leq r \leq b - 1 & \\
    \text{STEP } 2& b = q_2 r_1 + r_2 & 0 \leq r_2 < r_1 & 162 = 3 \cdot 48 + 18 \\
    & r_1 = q_3 r_2 + r_3 & 0 < r_3 < r_2 & 48 = 2 \cdot 18 + 12 \\
    & \vdots &  & 18 = 1 \cdot 12 + 6 \\
    \text{STEP } n& r_{n - 2} = q_n r_{n-1} + r_{n} & 0 \leq r_n < r_{n - 1} & 12 = 2 \cdot 6 \\
    \text{STEP } n + 1& r_{n - 1} = q_{n + 1} r_n + r_{n + 1} & r_{n + 1} = 0 & 0 \leq r_n < r_{n - 1} & \\
    \hline
    \text{OUTPUT} & r_n &&&
\end{array} 
Note that the algorithm terminates in $\leq b$ steps, since $b > r_1 > r_2 > \ldots \geq 0$.

::: {.theorem}
The output of Euclid's algorithm with input $a, b$ is $\operatorname{hcf}(a, b)$.
:::
::: {.proof}
\ 

i. We can see $r_n / r_{n - 1}$ (as $r_{n + 1} = 0$ at STEP $n + 1$)
so $r_{n - 1} / r_{n - 2}$  STEP $n$
\begin{align*}
    \text{We can see } &r_n \mid r_{n - 1} \text{ (as } r_{n + 1} = 0 \text{  at STEP } n + 1 \\
    \text{so } &r_n \mid r_{n - 2} \ ( \text{STEP } n) \\
    \text{so } &r_n \mid r_i \; \forall \; i = 1, \ldots n - 1 \text{ (by induction)}
\end{align*} 
Hence $r_n \mid b$ (STEP $2$) and $r_n \mid a$ (STEP $1$).

ii. Given $d$ s.t. $d \mid a$ and $d \mid b$,
\begin{align*}
    \text{we have } &d \mid r_1 \text{ (STEP 1) } \\
    \text{so } &d \mid r_2 \text{ (STEP 1) } \\
    \text{so } &d \mid r_i \; \forall \; i = 1, \ldots n \text{ (by induction)}
\end{align*} 
Therefore, $r_n = \operatorname{hcf}(a, b)$.
:::