# Countability

We would like to talk about sizes of infinite sets e.g. $\mathbb{N}$ "looks smaller than" $\mathbb{Z}$, and a lot smaller than $\mathbb{Q}$, which in turn looks smaller that $\mathbb{R}$.

::: {.definition name="Countable sets"}
We say a set $X$ is *countable* if $X$ is finite or there is a bijection $X \to \mathbb{N}$.
That is $X$ is countable iff we can list the elements of $X$ as $x_1, x_2, x_3, \ldots$ (will terminate if finite set).
:::

::: {.example}

\

1. Any finite set is countable.

2. $\mathbb{N}$ is countable.

3. $\mathbb{Z}$ is countable, as we may $\mathbb{Z}$ as $0, 1, -1, 2, -2, 3 \ldots$ i.e. $x_n = \begin{cases}
    \frac{n}{2} & \text{if $n$ is even} \\
    -\frac{n - 1}{2} & \text{if $n$ is odd}.
\end{cases}$
:::

::: {.lemma #vone}
Any subset of $\mathbb{N}$ is countable.
:::

::: {.proof}
If $S \subseteq N$ is non-empty, by WOP (well ordering principle) there is a least element $s_1 \in S$.
If $S \setminus \{s_1\} \neq \emptyset$, by WOP there is a least element $s_2 \in S_1 \setminus \{s_1, s_2\} \neq \emptyset \ldots$
If at some point this process stops, then $S = \{s_1, s_2, \ldots, s_m\}$ is finite.
If it goes on forever, the map $g : \mathbb{N} \to S$ given by $g(n) = s_n$ is well defined (for every $n$, there is a unique $s_n$) and is injective.
It is also surjective because if $k \in S$, then $k \in \mathbb{N}$, and there are $< k$ elements of $S$ less than $k$, so $k = s_n$ for some $n \leq k$.
:::

*Warning* In $\mathbb{R}$, let $S = \left\{\frac{1}{2}, \frac{2}{3}, \frac{3}{4}, \ldots\right\} \cup \{1\}$, then $S$ is countable as we can list it as $1, \frac{1}{2}, \frac{3}{4}, \ldots$ but if we have tried to list the elements in increasing order (as in the proof of Lemma \@ref(lem:vone) then $1$ would not be on the list).

::: {.theorem #vtwo}
The following statements are equivalent:

1. $X$ is countable;

2. There is an injection $X \to \mathbb{N}$;

3. $X = \emptyset$ or there is a surjection $\mathbb{N} \to X$.
:::

::: {.proof}
Plainly (i) $\implies$ (ii) for if $X$ is finite, it obviously injects into $\mathbb{N}$, and if $X$ bijects with $\mathbb{N}$, then it certainly injects into $\mathbb{N}$.\
Conversely, if there is an injection $f : X \to \mathbb{N}$, then $f$ is a bijection between $X$ and $S = f(X)$.
If $S$ is finite, then so is $X$.
If $S$ is infinite, then by Lemma \@ref(lem:vone), there is a bijection $g : S \to \mathbb{N}$, and thus $X \overset{f}{\to} S = f(X) \overset{g}{\to} \mathbb{N}$ is a bijection.
So (ii) $\implies$ (i).
Plainly (i) $\implies$ (iii), if $X \neq \emptyset$ and there is a surjection $f : \mathbb{N} \to X$, define $g : X \to \mathbb{N}$ by $g(a) = \min f^{-1}(\{a\})$, which exists by WOP.
$g$ is injective, so by (ii), $X$ is countable, i.e. (iii) $\implies$ (i).
:::

::: {.corollary #vthree}
Any subset of a countable set is countable.
:::

::: {.proof}
If $Y \subseteq X$ and $X$ is countable, then take the injection $X \to \mathbb{N}$ restricted to $Y$.
:::

We may thus view "countable" as meaning as saying a set is "at most as big as $\mathbb{N}$".

::: {.theorem #vfour}
$\mathbb{N} \times \mathbb{N}$ is countable.
:::

::: {.proof name="1"}
Define $a_1 = (1, 1)$ and $a_n$ inductively by, writing $a_{n-1} = (p, q)$, 
\begin{align*}
    a_n = \begin{cases}
        (p - 1, q + 1) & p \neq 1 \\
        (p + q, 1) & \text{otherwise.}
    \end{cases}
\end{align*} 
This list includes every point $(x, y) \in \mathbb{N} \times \mathbb{N}$ by induction on $x + y$.
:::

::: {.proof name="2"}
Define
\begin{align*}
    f : \mathbb{N} \times \mathbb{N} &\to \mathbb{N} \\
    (x, y) &\mapsto 2^x 3^y.
\end{align*}
Then $f$ is injective by \@ref(thm:fta)
:::

::: {.corollary}
$\mathbb{Z} \times \mathbb{Z}$ is countable
:::
::: {.proof}
Since $\mathbb{Z}$ is countable, there is an injection $\mathbb{Z} \to \mathbb{N}$, so because $\mathbb{N} \to \mathbb{N}$ is countable, we have an injection $\mathbb{Z} \times \mathbb{Z} \to \mathbb{N} \times \mathbb{N} \to \mathbb{N}$.
:::

By induction $\mathbb{Z}^k$ is countable for any $k \in \mathbb{N}$.

::: {.theorem #vsix}
A countable union of countable sets is countable (a countable union is a union of sets that are indexed by a countable set)
:::
::: {.proof name="1"}
We may assume that our countable sets are indexed by $\mathbb{N}$, so given countable sets $A_1, A_2 A_3, \ldots$ we wish to show $\bigcup_{n \in \mathbb{N}} A_n$ is countable. \
For each $i \in \mathbb{N}$, since $A_i$ is countable, we may list its elements as $a_1^{(i)}, a_2^{(i)}, a_3^{(i)}$ (might terminate).
Define \begin{align*}
    f : \bigcup_{n \in \mathbb{N}} A_n &\to \mathbb{N} \\
    x &\mapsto 2^i 3^j
\end{align*} where $x = a_j^{(i)}$ for the least $i$ s.t. $x \in A_i$ (as $x$ could be in more than of the $A_i$'s).
This is an injection.
:::
::: {.proof name="2"}
Let $I$ be a countable index set, and for each $i \in I$, $A_i$ is a countable set.
Since $I$ is countable, there is an injection $f : I \to \mathbb{N}$ and for each $i \in I$, since $A$ is countable, there is an injection $g_i :A_i \to \mathbb{N}$. \
We construct an injection $h : A = \bigcup_{i \in I} A_i \to \mathbb{N} \times \mathbb{N}$ as follows for each $x \in A$, pick $m_x = \min \{j \in \mathbb{N},\ x \in A_i,\ f(i) = j\}$, which exists by WOP.
Let $i_x$ be such that $f(i_x) = m_x$ ($i_x$ is unique as $f$ is injective).
Set $h(x) = (m_x, g_{i_x}(x))$.
Then $h$ is an injection.
:::

::: {.example}
$\mathbb{Q} = \bigcup_{n \in \mathbb{N}} \frac{1}{n} \mathbb{Z} = \bigcup_{n \in \mathbb{N}} \left\{ \frac{m}{n} : m \in \mathbb{Z} \right\}$, so $\mathbb{Q}$ is a countable union of countable sets, hence countable.
:::

::: {.theorem #vseven}
The set $\mathbb{A}$ of algebraic numbers is countable.
:::
::: {.proof}
It suffices to show that the set of all polynomials with integer coefficients is countable as then $\mathbb{A}$ is a countable union of finite sets, so by Theorem \@ref(thm:vsix), is countable.
In fact, it suffices to show that for each $d \in \mathbb{N}$, the set $P_d$ of all integer polynomials of degree $d$ is countable, again by Theorem \@ref(thm:vsix).
But the map $P_d \to \mathbb{Z}^{d + 1}$, $p(x) = a_d x^d + a_{d-1}x^{d-1} + \ldots + a_1 x + a_0 \mapsto (a_d, a_{d-1}, \ldots, a_1, a_0)$ is an injection, so since $\mathbb{Z}^{d + 1}$ is countable, $P_d$ is countable.
:::
A set is *uncountable* if it is not countable.
Do uncountable sets exist?

::: {.theorem #veight}
$\mathbb{R}$ is uncountable.
:::
::: {.proof}
If $\mathbb{R}$ were countable, we would be able to list all the reals as $r_1, r_2, r_3, \ldots$
Write each $r_n$ in decimal form in some way.
\begin{align*}
    r_1 &= n_1.d_{11} d_{12} d_{13} d_{14} \ldots \\
    r_2 &= n_2.d_{21} d_{22} d_{23} d_{24} \ldots \\
    r_3 &= n_3.d_{31} d_{32} d_{33} d_{34} \ldots \\
    &\;\;\vdots
\end{align*} 
Define $r = 0.d_1 d_2 d_3 \ldots$ by $d_n = \begin{cases}
    1 & \text{if } d_{nn} \neq 1 \\
    2 & \text{if } d_{nn} = 1
\end{cases}.$
This $r$ has only one decimal expansion and is not on the list (because $\forall \; n \in \mathbb{N}, r \neq r_n$) which is a contradiction.
:::
